
  <h2>Liste des <?= $c['categorie'] ?> </h2>


<article class="">


  <?php foreach($plat as $p): ?>

    <p><img  class="" src="<?= $wwwUrl ?>/images/meals/<?= $p['photo'] ?>"/></p>
    <p><span  class="">entrée : </span><em><?= $p['nom'] ?></em></p>
    <p><span  class="">Contenue : </span><em><?= $p['description'] ?></em></p>
    <p><span  class="">Prix : </span><em><?= $p['prix'] ?> €</em></p>

  <?php endforeach; ?>

</article>
