<article class="">
  <h2>Bienvenue : <?php echo $user['prenom'] ?></h2>
  <p><strong>voici vos informations, conservez-les précieusement !</strong></p>
  <p><span  class="user">Votre pseudo : </span><em><?= $user['pseudo'] ?></em></p>
  <p><span  class="user">Votre mail :</span><em><?= $user['email'] ?></em></p>
  <p><span  class="user">Votre mot de passe : </span><em><?= $user['password'] ?></em></p>
</article>
