<p class="layout-center"><?= $newuser ?></p>

<form action="" method="post" id="subscribe">
  <fieldset>
    <legend>Inscription</legend>

    <label for="name">Nom</label>
    <input type="text" id="username" name="name" placeholder="Jean">

    <label for="firstname">Prenom</label>
    <input type="text" id="username" name="firstname" placeholder="Francois">

    <label for="pseudo">pseudo</label>
    <input type="text" id="username" name="pseudo" placeholder="superman">

    <label for="password">Password</label>
    <input id="password" name="password" placeholder="********">

    <label for="mail"/>votre email :</label>
    <input type="email" name="mail" placeholder="exemple@gmail.fr"/>

    <label for="phone">Enter your phone number:</label>
    <input type="tel" id="phone" name="phone">

    <label for="adresse"/>Adresse</label>
    <input type="text" name="adresse"/>

    <button type="submit">Je m'inscris !</button>
    <button><a href="index.php"><i class="fas fa-undo"></i>Annuler</a></button>
  </fieldset>
</form>
