<form action="" method="post" id="subscribe">
  <fieldset>
    <legend>connexion</legend>

    <label for="pseudo">Votre pseudo</label>
    <input type="text" id="username" name="pseudo" placeholder="superman">

    <label for="password">Password</label>
    <input id="password" name="password" placeholder="********">

    <button type="submit" class="details">Se connecter</button>
    <button class="details"><a href="<?= $requestUrl ?>"><i class="fas fa-undo-alt"></i>Annuler</a></button>

  </fieldset>
</form>
